
name: Trickest Client

on:
  workflow_dispatch:

jobs:
  execute-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Set GitHub Token
      run: |
        echo "$SSH_KEY" > id_rsa
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}

    - name: Trickest Execute
      id: trickest
      uses: trickest/action@main
      env:
        TRICKEST_TOKEN: "${{ secrets.TRICKEST_TOKEN }}"
      with:
        workflow: "Github Recon & Scanner"
        space: "Github Recon & Scanner"
        project: "Base Project"
        create_structure: true
        config_path: config.yaml
